spring.application.name=shop

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.h2.console.path=/h2-console

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Security config
#spring.security.user.name=user1
#spring.security.user.password=123456

# Jwt configs
spring.app.jwtExpirationMs=100000000
spring.app.jwtSecret=${JWTSECRET}
spring.app.jwtCookieName=phamminhhoang

# VNPay Configuration
vnpay.tmnCode=${VNPAY_TMN_CODE}
vnpay.hashSecret=${VNPAY_HASH_SECRET}
vnpay.payUrl=${VNPAY_PAY_URL}
vnpay.apiUrl=${VNPAY_API_URL}
vnpay.returnUrl=${VNPAY_RETURN_URL}
vnpay.notifyUrl=${VNPAY_NOTIFY_URL}

# Logs
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.security_demo=DEBUG