spring.application.name=shop

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.h2.console.path=/h2-console

# Security config
spring.security.user.name=user1
spring.security.user.password=123456

# Jwt configs
spring.app.jwtExpirationMs=100000000
spring.app.jwtSecret=phamminhhoang123287138asdalsjdklajs80912839081290381290381jkasjekljaslkdjkalsjdlas01823
spring.app.jwtCookieName=phamminhhoang